RETWEETED_STATUS_KEY = 'retweeted_status'
USER_KEY = 'user'
SCREEN_NAME_KEY = 'screen_name'
USER_MENTIONS_KEY = 'user_mentions'
IN_REPLY_TO_SCREEN_NAME_KEY = 'in_reply_to_screen_name'
RETWEETS_KEY = 'retweets'
COMMENTS_KEY = 'comments'
MENTIONS_KEY = 'mentions'

consumer_id_key = 'NC19WDNaMoEaaV9s8nadVUvBI'
consumer_secret_key = 'rtoYVT9AykdYQWWv5Nh7ZdDode72DRSLX8XswRrqprxhC2TnI3'
access_token_key = '1058944938887409664-402KNxXTgNNhMoAK3pmAUziB3Fhxzj'
access_token_secret = 'vVxGZQdN9ubMK1EnxZGx62ZsxVqwFQiwDZmXmEMfPYSKj'
